### ISSUE TITLE
[Backport request] Is it possible to get a 1.20.1 version?

### ISSUE THREAD

**Issue by ShyVaporeon** [SirDoomTurtle/Elytra-Rebalance#1]
I have a custom Vanilla++ modpack on 1.20.1, which is is a version still very popular for modding, and this mod would fit in perfectly. Is there any chance of getting a 1.20.1 version?

**Comment by SirDoomTurtle** [comment]
I probably won't backport this mod, because it was/is my very first attempt at making a mod, and it did not meet my expectations. You can however use this repo and backport it yourself if you want to, I have no problems with that.
